name: complex

on: push

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - run: date 

  windows:
    runs-on: windows-latest
    steps:
      - run: Get-Date

  macos:
    runs-on: macos-latest
    steps:
      - runs: date

  depends:
    runs-on: centos-latest
    steps:
      - runs: date
    needs: [ubuntu, windows, macos]
