name: complex

on: push

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: date

  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - run: date

  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - run: date

  depends:
    runs-on: centos-latest
    needs: [ubuntu, windows, macos]
    steps:
      - uses: actions/checkout@v4
      - run: date
