name: complex

on: push

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        run: date 

  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        run: Get-Date

  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        runs: date

  depends:
    runs-on: centos-latest
    steps:
      - uses: actions/checkout@v4
        runs: date
    needs: [ubuntu, windows, macos]
